apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    alertmanagerMain:
      volumeClaimTemplate:
        spec:
          storageClassName: thin
          resources:
            requests:
              storage: 10G
    prometheusK8s:
      volumeClaimTemplate:
        spec:
         storageClassName: thin
         resources:
           requests:
             storage: 10G
