apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: ldap-ipa
    mappingMethod: claim
    type: LDAP
    ldap:
      attributes:
        id:
        - dn
        email:
        - mail
        name:
        - cn
        preferredUsername:
        - uid
      bindDN: "uid=admin,cn=users,cn=accounts,dc=randalllabs,dc=com"
      bindPassword:
        name: ldap-secret
      ca:
        name: ca-config-map
      insecure: false
      url: "ldaps://bast-idm.randalllabs.com:636/cn=users,cn=accounts,dc=randalllabs,dc=com?uid??(memberOf=cn=openshift4,cn=groups,cn=accounts,dc=randalllabs,dc=com)"

