apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cert-manager-operator
  namespace: openshift-cert-manager-operator
spec:
  channel: tech-preview
  name: cert-manager-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace 