apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
  creationTimestamp: null
  labels:
    machine.openshift.io/cluster-api-cluster: vmware-lnzv5
  name: vmware-lnzv5-worker
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: vmware-lnzv5
      machine.openshift.io/cluster-api-machineset: vmware-lnzv5-worker
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: vmware-lnzv5
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: vmware-lnzv5-worker
    spec:
      metadata:
        creationTimestamp: null
        labels:
          node-role.kubernetes.io/worker: ""
      providerSpec:
        value:
          apiVersion: machine.openshift.io/v1beta1
          credentialsSecret:
            name: vsphere-cloud-credentials
          diskGiB: 120
          kind: VSphereMachineProviderSpec
          memoryMiB: 8192 
          metadata:
            creationTimestamp: null
          network:
            devices:
            - networkName: LNX
          numCPUs: 2
          numCoresPerSocket: 2
          snapshot: ""
          template: vmware-lnzv5-rhcos
          userDataSecret:
            name: worker-user-data
          workspace:
            datacenter: BasementRack
            datastore: QNAP-ISCSI-THIN
            folder: /BasementRack/vm/vmware-lnzv5
            resourcePool: /BasementRack/host/DL360G9/Resources
            server: vcenter.randalllabs.com