apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  creationTimestamp: null
  finalizers:
  - ingresscontroller.operator.openshift.io/finalizer-ingresscontroller
  name: default
  namespace: openshift-ingress-operator
spec:
  clientTLS:
    clientCA:
      name: ""
    clientCertificatePolicy: ""
  httpCompression: {}
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ""
  replicas: 2
  tuningOptions: {}
  unsupportedConfigOverrides: null
  nodePlacement:
    nodeSelector:
      matchLabels: 
        node-role.kubernetes.io/infra: ""