apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: automationcontroller
    app.kubernetes.io/managed-by: automationcontroller-operator
    app.kubernetes.io/name: test-aap
    app.kubernetes.io/operator-version: ''
    app.kubernetes.io/part-of: test-aap
  name: test-aap
  namespace: openshift-machine-api
spec:
  create_preload_data: true
  route_tls_termination_mechanism: Edge
  garbage_collect_secrets: false
  ingress_type: Route
  loadbalancer_port: 80
  image_pull_policy: IfNotPresent
  projects_storage_size: 8Gi
  task_privileged: false
  projects_storage_access_mode: ReadWriteMany
  projects_persistence: false
  replicas: 1
  admin_user: admin
  loadbalancer_protocol: http
  nodeport_port: 30080